### ISSUE TITLE
Date of event

### ISSUE THREAD

**Issue by harsh500** [Deepak-Sangle/mIIT-Kute#4]
There is no date of event and as your app is mainly for social interaction I think sometime it could be hard to gather people within 24 hrs so it would be great if we can give the date also

**Comment by ris27hav** [comment]
Also, one can set the end time before the start time, which should throw an error, but the system accepts it.

**Comment by Deepak-Sangle** [comment]
Issue I: Since the scope of the app is small, we restricted ourselves to search an event in around 24hrs only. 
Issue II : This issue is now fixed and the user would get an alert if he sets the starting time earlier than the end time.
