### ISSUE TITLE
Profile Photo Error

### ISSUE THREAD

**Issue by AdiPratapSingh** [Deepak-Sangle/mIIT-Kute#8]
I want to update my profile but I am getting an internal server error when I try that. Could you please fix this issue?

**Comment by Deepak-Sangle** [comment]
Dear @AdiPratapSingh, 
Phase 1 of beta testing has been long past its due date (17th April). You raised the issue on the 24th of April. If you really want to contribute to our product, feel free to reopen the issue after endsem (May 5).  

Thanks.

**Comment by Deepak-Sangle** [comment]
Dear @AdiPratapSingh,
This error is now fixed. Now one can change his/her profile picture without any error. Feel free to reopen the issue if this is not a satisfactory or relevant reply.

Thank you.
